### ISSUE TITLE
Runtime error on Windows 10/Outputting grayscale depthmapcs

### ISSUE THREAD

**Issue by herrartist** [compphoto/SIDepth#2]
I get this error: Runtime error. Attempting to deserialize object on a CUDA device but torch.cuda is available() is false. If you are running on a CPU only machine please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

My Windows 10 PC has this card: NVIDIA GeoForce RTX 3080 Ti.

How can I solve this?

I would also like to output grayscale images (depthmaps) from a batch of single video frames. How can I do this?

**Comment by miangoleh** [comment]
Our instructions use PIP to install dependencies. This expects you to install Cuda dependencies on your system beforehand. Another easier workaround is to use conda instead of pip for torch. You can run the following commands in a fresh environment to install cuda dependencies as well:

```
conda create -n newsidepthenv python=3.8
conda activate newsidepthenv 
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
pip install opencv-python timm tqdm yacs scikit-image
```

Then you can run the python script using the new env


I tested this on Windows11 with an NVIDIA RTX 1080 ti and it worked. I assume it should solve your issue. 

As you said you can feed a batch of video frames through the network but you will need to modify our code and implement it for yourself as we did not implement this. If you'd like to use our implementation as is, I suggest decomposing the video into a sequence of PNG files and running our method on those. It adds some I/O overheads but the results should be the same.

**Comment by herrartist** [comment]
Thank you very much! It works now! But how can I render grayscale images (depthmaps) instead of the colorized pictures?

**Comment by miangoleh** [comment]
Remove —colorize
